language: python
sudo: false
python:
  - "3.7"
  - "3.8"
deploy:
  provider: pypi
  user: vemund
  password:
    secure: Qpgj47A35osBQRX4uAbRCCY2lcaswK2LH+nBQArLjChTEibJESIOuXYfDV0Hu8YF4z20pLUMuHyzP2Kb2c2lU0p0BwY8/5dxNWKOaFVUNDSnLr3BjF27COpphkapOuyI6lvD7Ejk/d9USjW7MMcTBaM6I9EU8iKi76tFbAUoq2sx38V8pCAaIzeIEGpWZheKL5U5mpmhQuqXribQAwsQE47S3QtgC0LZ2f6ucYXb7biyRC43gvqvKitR4byJUfFg/7CPml0nfDZPLyoPb49P/rPCQzt0SaE9ECzsK47HWgq2jbplKdJMA/z2VJOXzAP8WIptLPhjMs086TVCz1p5CyIPBl1q95gNksz32bUUflKjfcWoK3DI76qENfwrxzQLtTVXiUmJwBVFPqwC1BbK/Oqf69P7eAoa5OzQCECGJTqjEkhXfKoPsT4eFoO4oh5ybseMM6En7i+JFMkC6UR8feI7AhezzCtMFfmjdpS3fEediUxm55Y4Nv6V9OJx2KimH8LzaUGtKpCVUx5HPSDANIsrQiK2D1ZtVa46OWNtkpBd1LRT0V87Z8AtA/11RSujO0vJsgI7YOaCtw2ObRRxYHjYG2xQuf4yMq05XYOYS6SwRjsfhxqgDPteXheCyB0FCPoDaHjiNkJKe7eCT2Dx6MRjzgDvMComjt3qtgmuscU=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.7
install:
  - pip install tox-travis
  - pip install codecov
script:
  - tox